# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nick_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('telephone', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date_of_order', models.DateTimeField()),
                ('date_of_accept', models.DateTimeField()),
                ('date_prognosis_act', models.DateTimeField()),
                ('date_fact_act', models.DateTimeField()),
                ('name_Goods', models.ManyToManyField(to='clientorder.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_cafe', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='grouporder',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientorder.UserProfile'),
        ),
        migrations.AddField(
            model_name='grouporder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientorder.Client'),
        ),
        migrations.AddField(
            model_name='grouporder',
            name='order',
            field=models.ManyToManyField(to='clientorder.Order'),
        ),
    ]
