# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='geoPosition',
            field=models.CharField(max_length=244, null=True),
        ),
    ]
